# Generated by Django 3.1.7 on 2021-06-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dersler',
            options={'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='odevler',
            options={'verbose_name_plural': 'Ödevler'},
        ),
        migrations.AlterModelOptions(
            name='ogrenciler',
            options={'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.AlterModelOptions(
            name='ogretmenler',
            options={'verbose_name_plural': 'Öğretmenler'},
        ),
        migrations.AlterModelOptions(
            name='siniflar',
            options={'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
