# Generated by Django 3.1.7 on 2021-05-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sinav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dersler'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(choices=[('1.Sınav', '1.Sınav'), ('2.Sınav', '2.Sınav'), ('3.Sınav', '3.Sınav')], max_length=7),
        ),
    ]
