# Generated by Django 3.1.7 on 2021-06-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0003_quiz_sinif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Sınavlar'},
        ),
    ]
