# Generated by Django 3.1.7 on 2021-06-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Cevaplar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Sorular'},
        ),
    ]
