# Generated by Django 3.1.7 on 2021-05-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odev_Konu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=500)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dersler')),
            ],
        ),
        migrations.CreateModel(
            name='Yuklenen_Odev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='odevler')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('odev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odev.odev_konu')),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ogrenciler')),
            ],
        ),
    ]
