# Generated by Django 3.1.7 on 2021-06-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odev_konu',
            options={'verbose_name_plural': 'Ödevler'},
        ),
        migrations.AlterModelOptions(
            name='yuklenen_odev',
            options={'verbose_name_plural': 'Yüklenen Ödevler'},
        ),
    ]
