# Generated by Django 3.1.7 on 2021-04-25 08:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='program_1', max_length=20)),
                ('pazartesi', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=160, size=10, verbose_name='Pazartesi')),
                ('sali', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=160, size=10, verbose_name='Salı')),
                ('carsamba', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=160, size=10, verbose_name='Çarşamba')),
                ('persembe', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=160, size=10, verbose_name='Perşembe')),
                ('cuma', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=160, size=10, verbose_name='Cuma')),
            ],
        ),
    ]
