# Generated by Django 3.1.7 on 2021-06-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210607_1720'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Ders Programları'},
        ),
        migrations.AddField(
            model_name='program',
            name='sinif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.siniflar'),
        ),
    ]
